/**
 * Seeds the `words` collection from lcdictionary.json (SCOWL UK, 1800 words).
 * Falls back to the built-in wordList.ts stub if the JSON is not found.
 *
 * Run: ts-node src/seeds/seedWords.ts
 *
 * To plug in an updated word list, replace:
 *   /Users/vinayakneeralli/Claude/Personal/lcdictionary.json
 * with any JSON array matching { word, length, difficulty, pos, lastUsed, useCount }
 */

import dotenv from 'dotenv';
import path from 'path';
dotenv.config({ path: path.join(__dirname, '../../.env'), override: true });

import fs from 'fs';
import mongoose from 'mongoose';
import { Word } from '../models/Word';
import { WORD_LIST } from './wordList';

// Primary source: SCOWL UK dictionary generated by gen_words_scowl.py
// __dirname = .../learncrosswords/backend/src/seeds → go up 4 levels to reach Claude/Personal/
const SCOWL_PATH = path.join(
  __dirname,
  '../../../../lcdictionary.json'
);

function loadWordList() {
  if (fs.existsSync(SCOWL_PATH)) {
    console.log(`  Using SCOWL dictionary: ${SCOWL_PATH}`);
    const raw = fs.readFileSync(SCOWL_PATH, 'utf-8');
    return JSON.parse(raw);
  }
  console.log('  SCOWL file not found — falling back to built-in wordList.ts stub');
  return WORD_LIST;
}

async function seedWords() {
  await mongoose.connect(process.env.MONGODB_URI!);
  console.log('✓ Connected to MongoDB');

  const words = loadWordList();
  console.log(`  Loaded ${words.length} words`);

  // Clear existing
  const deleted = await Word.deleteMany({});
  console.log(`✓ Cleared ${deleted.deletedCount} existing words`);

  // Insert in batches of 500 to avoid document size limits
  const BATCH = 500;
  let inserted = 0;
  for (let i = 0; i < words.length; i += BATCH) {
    const batch = words.slice(i, i + BATCH);
    await Word.insertMany(batch, { ordered: false });
    inserted += batch.length;
    process.stdout.write(`\r  Inserted ${inserted}/${words.length}...`);
  }
  console.log(`\n✓ Inserted ${inserted} words`);

  // Summary
  const counts = await Word.aggregate([
    { $group: { _id: '$difficulty', count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]);
  console.log(
    '  Distribution:',
    counts.map((c: any) => `${c._id}: ${c.count}`).join(', ')
  );

  await mongoose.disconnect();
  console.log('✓ Done');
}

seedWords().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
