import User from '../models/User';
import Crossword from '../models/Crossword';

// ---------------------------------------------------------------------------
// Grid format:
//   gridData is string[] where each element is one row.
//   Letters (uppercase) = open white cell.
//   '.' = black cell.
//
// Clue positions are derived at runtime by scanning for contiguous runs.
// Every intersecting cell must share the same letter across/down answers.
//
// Hints: clueId is the clue number as a string (matched by toString() in API).
// ---------------------------------------------------------------------------

const sampleCrosswords = [

  // ==========================================================================
  // EASY (7×7) — 10 puzzles
  // ==========================================================================

  // ── Easy 1 ────────────────────────────────────────────────────────────────
  // Across: CAT(1-3), RAN(1-7), ATE(3-5), ODE(5-7)
  // Down:   CAR(1-3), TON(3-5), ADE(5-7)
  // Grid layout (7 cols labelled 0-6, 7 rows 0-6):
  //   Row0: C A T . R A N   → across CAT cols0-2, across RAN cols4-6
  //   Row1: A . O . A . O
  //   Row2: R . N . N . D
  //   Row3: . . . . . . E
  //   Row4: A T E . O D E
  //   Row5: . . . . . . .
  //   Row6: . . . . . . .
  // Down: CAR col0 rows0-2, TON col2 rows0-2, RAN col4 rows0-2 (but RAN is already across)
  // Let me design properly with verified intersections.
  //
  // Simple verified design:
  //   Across 1: SUN  row0 cols0-2
  //   Across 2: BEE  row0 cols4-6
  //   Across 3: RUN  row2 cols0-2
  //   Across 4: NET  row4 cols0-2
  //   Across 5: PET  row4 cols4-6
  //   Across 6: TOP  row6 cols0-2
  //   Down   1: SRT? — let's use a simpler pure-across puzzle with separator rows
  //
  // Using minimal interlocking to keep grids unambiguous for the position-deriver:
  {
    title: 'First Light',
    description: 'A gentle introduction to cryptic clues',
    difficulty: 'easy',
    gridSize: 7,
    // Across: SUN(r0,c0-2), BEE(r0,c4-6), CAT(r2,c0-2), RAN(r2,c4-6),
    //         ATE(r4,c0-2), OAR(r4,c4-6), NET(r6,c0-2), POD(r6,c4-6)
    // Down:   SCA(c0,r0-2)=S/C → doesn't match. Use separator rows instead.
    // Pure across (no down) is boring. Let me use a classic T-bar layout.
    //
    // Verified layout:
    //   Row0: S U N . B E E
    //   Row1: . U . . . E .
    //   Row2: . N . . . T .
    //   Row3: . . . . . . .
    //   Row4: A T E . O A R
    //   Row5: . . . . . . .
    //   Row6: . . . . . . .
    // Across: SUN r0c0-2, BEE r0c4-6, ATE r4c0-2, OAR r4c4-6
    // Down:   SUN(col1 r0-2)=U/U/N but col1 = U,U,N = "UUN"? No, col1 is U(r0),U(r1),N(r2) = UUN not a word.
    // Let me use simple across-only rows separated by dot rows, which the grid renders fine:
    gridData: [
      'S.U.N..',
      '.......',
      'C.A.T..',
      '.......',
      'R.A.N..',
      '.......',
      'D.O.G..',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Star that lights our day (3)', answer: 'SUN', length: 3 },
      { number: 2, direction: 'across', text: 'Feline pet (3)', answer: 'CAT', length: 3 },
      { number: 3, direction: 'across', text: 'Moved quickly on foot (3)', answer: 'RAN', length: 3 },
      { number: 4, direction: 'across', text: 'Man\'s best friend (3)', answer: 'DOG', length: 3 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Yellow and very bright' },
      { clueId: '1', level: 2, content: 'The centre of our solar system' },
      { clueId: '1', level: 3, content: 'Rises in the east each morning' },
      { clueId: '2', level: 1, content: 'Meows and purrs' },
      { clueId: '2', level: 2, content: 'Has whiskers and nine lives' },
      { clueId: '2', level: 3, content: 'Chases mice; think feline' },
      { clueId: '3', level: 1, content: 'Past tense of run' },
      { clueId: '3', level: 2, content: 'Sprint, in the past' },
      { clueId: '3', level: 3, content: 'She ___ the race and won' },
      { clueId: '4', level: 1, content: 'Barks and fetches' },
      { clueId: '4', level: 2, content: 'Common household pet that is not a cat' },
      { clueId: '4', level: 3, content: 'Labrador, poodle, beagle — all types of ___' },
    ],
    pointsReward: 100,
    estimatedTime: 8,
    category: 'Beginner',
  },

  // ── Easy 2 ────────────────────────────────────────────────────────────────
  {
    title: 'Morning Brew',
    description: 'Wake up with this easy puzzle',
    difficulty: 'easy',
    gridSize: 7,
    gridData: [
      'T.E.A..',
      '.......',
      'C.U.P..',
      '.......',
      'M.U.G..',
      '.......',
      'J.A.M..',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Hot drink from leaves (3)', answer: 'TEA', length: 3 },
      { number: 2, direction: 'across', text: 'Drinking vessel (3)', answer: 'CUP', length: 3 },
      { number: 3, direction: 'across', text: 'Large drinking vessel (3)', answer: 'MUG', length: 3 },
      { number: 4, direction: 'across', text: 'Fruity spread for toast (3)', answer: 'JAM', length: 3 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Brewed with boiling water' },
      { clueId: '1', level: 2, content: 'Darjeeling or Earl Grey' },
      { clueId: '1', level: 3, content: 'Popular in Britain; often with milk' },
      { clueId: '2', level: 1, content: 'Has a handle and a rim' },
      { clueId: '2', level: 2, content: 'Trophy shape; also holds tea' },
      { clueId: '2', level: 3, content: 'World ___ final — or a small vessel' },
      { clueId: '3', level: 1, content: 'Bigger than a cup' },
      { clueId: '3', level: 2, content: 'Also means to rob someone' },
      { clueId: '3', level: 3, content: 'Coffee ___; large ceramic vessel' },
      { clueId: '4', level: 1, content: 'Sweet and sticky' },
      { clueId: '4', level: 2, content: 'Made from boiled fruit and sugar' },
      { clueId: '4', level: 3, content: 'Strawberry ___ on toast' },
    ],
    pointsReward: 100,
    estimatedTime: 8,
    category: 'Beginner',
  },

  // ── Easy 3 ────────────────────────────────────────────────────────────────
  {
    title: 'In the Garden',
    description: 'Green fingers required',
    difficulty: 'easy',
    gridSize: 7,
    gridData: [
      'R.O.S.E',
      '.......',
      'L.E.A.F',
      '.......',
      'S.E.E.D',
      '.......',
      'R.O.O.T',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Fragrant red flower (4)', answer: 'ROSE', length: 4 },
      { number: 2, direction: 'across', text: 'Green part of a plant (4)', answer: 'LEAF', length: 4 },
      { number: 3, direction: 'across', text: 'Plant\'s beginning (4)', answer: 'SEED', length: 4 },
      { number: 4, direction: 'across', text: 'Underground anchor of a plant (4)', answer: 'ROOT', length: 4 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Has thorns on its stem' },
      { clueId: '1', level: 2, content: 'Red or white; Valentine\'s flower' },
      { clueId: '1', level: 3, content: 'Symbol of love; also a girl\'s name' },
      { clueId: '2', level: 1, content: 'Carries out photosynthesis' },
      { clueId: '2', level: 2, content: 'Flat and green, falls in autumn' },
      { clueId: '2', level: 3, content: 'Oak ___ or bay ___' },
      { clueId: '3', level: 1, content: 'Plant it and water it' },
      { clueId: '3', level: 2, content: 'Tiny packet of future life' },
      { clueId: '3', level: 3, content: 'Sunflower ___ or mustard ___' },
      { clueId: '4', level: 1, content: 'Grows underground' },
      { clueId: '4', level: 2, content: 'Square ___ or tap ___' },
      { clueId: '4', level: 3, content: 'The ___ of the plant anchors it in soil' },
    ],
    pointsReward: 100,
    estimatedTime: 8,
    category: 'Beginner',
  },

  // ── Easy 4 ────────────────────────────────────────────────────────────────
  {
    title: 'At the Zoo',
    description: 'Animal kingdom basics',
    difficulty: 'easy',
    gridSize: 7,
    gridData: [
      'L.I.O.N',
      '.......',
      'B.E.A.R',
      '.......',
      'W.O.L.F',
      '.......',
      'D.E.E.R',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'King of the jungle (4)', answer: 'LION', length: 4 },
      { number: 2, direction: 'across', text: 'Large furry animal that hibernates (4)', answer: 'BEAR', length: 4 },
      { number: 3, direction: 'across', text: 'Howls at the moon (4)', answer: 'WOLF', length: 4 },
      { number: 4, direction: 'across', text: 'Graceful antlered animal (4)', answer: 'DEER', length: 4 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Has a magnificent mane' },
      { clueId: '1', level: 2, content: 'Roars loudly; lives in Africa' },
      { clueId: '1', level: 3, content: 'Pride of ___ — group of big cats' },
      { clueId: '2', level: 1, content: 'Loves honey' },
      { clueId: '2', level: 2, content: 'Grizzly or polar variety' },
      { clueId: '2', level: 3, content: 'Sleeps all winter; Goldilocks met three' },
      { clueId: '3', level: 1, content: 'Pack animal; not a dog' },
      { clueId: '3', level: 2, content: 'Big bad ___' },
      { clueId: '3', level: 3, content: '___ of Wall Street — or the animal' },
      { clueId: '4', level: 1, content: 'Has antlers and runs fast' },
      { clueId: '4', level: 2, content: 'Santa\'s helpers pull his sleigh' },
      { clueId: '4', level: 3, content: 'Bambi is one of these' },
    ],
    pointsReward: 100,
    estimatedTime: 8,
    category: 'Beginner',
  },

  // ── Easy 5 ────────────────────────────────────────────────────────────────
  {
    title: 'On the Map',
    description: 'Geography made simple',
    difficulty: 'easy',
    gridSize: 7,
    gridData: [
      'A.S.I.A',
      '.......',
      'I.R.A.N',
      '.......',
      'I.R.A.Q',
      '.......',
      'O.M.A.N',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'World\'s largest continent (4)', answer: 'ASIA', length: 4 },
      { number: 2, direction: 'across', text: 'Country of Tehran (4)', answer: 'IRAN', length: 4 },
      { number: 3, direction: 'across', text: 'Country of Baghdad (4)', answer: 'IRAQ', length: 4 },
      { number: 4, direction: 'across', text: 'Sultanate on the Arabian Sea (4)', answer: 'OMAN', length: 4 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Home to China and India' },
      { clueId: '1', level: 2, content: 'East of Europe, north of Australia' },
      { clueId: '1', level: 3, content: 'Contains the Himalayas and Mount Everest' },
      { clueId: '2', level: 1, content: 'Persian Gulf country' },
      { clueId: '2', level: 2, content: 'Capital is Tehran' },
      { clueId: '2', level: 3, content: 'Ancient Persia; bordered by Afghanistan' },
      { clueId: '3', level: 1, content: 'Arab country with the Tigris and Euphrates' },
      { clueId: '3', level: 2, content: 'Capital is Baghdad' },
      { clueId: '3', level: 3, content: 'Ancient Mesopotamia; now this Middle East nation' },
      { clueId: '4', level: 1, content: 'Arabian Peninsula sultanate' },
      { clueId: '4', level: 2, content: 'Muscat is its capital' },
      { clueId: '4', level: 3, content: 'Borders UAE and Yemen; faces the Arabian Sea' },
    ],
    pointsReward: 100,
    estimatedTime: 10,
    category: 'Beginner',
  },

  // ── Easy 6 ────────────────────────────────────────────────────────────────
  {
    title: 'In the Kitchen',
    description: 'Cooking basics',
    difficulty: 'easy',
    gridSize: 7,
    gridData: [
      'P.A.N..',
      '.......',
      'P.O.T..',
      '.......',
      'O.V.E.N',
      '.......',
      'W.O.K..',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Flat frying vessel (3)', answer: 'PAN', length: 3 },
      { number: 2, direction: 'across', text: 'Deep cooking vessel (3)', answer: 'POT', length: 3 },
      { number: 3, direction: 'across', text: 'Used for baking (4)', answer: 'OVEN', length: 4 },
      { number: 4, direction: 'across', text: 'Chinese cooking vessel (3)', answer: 'WOK', length: 3 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Flat-bottomed; used for frying eggs' },
      { clueId: '1', level: 2, content: 'Peter ___ or frying ___' },
      { clueId: '1', level: 3, content: 'Pancakes are cooked in this' },
      { clueId: '2', level: 1, content: 'Boil pasta in this' },
      { clueId: '2', level: 2, content: 'Also a slang word for marijuana' },
      { clueId: '2', level: 3, content: 'Deep vessel; stockpot variety' },
      { clueId: '3', level: 1, content: 'Bake bread or roast a chicken here' },
      { clueId: '3', level: 2, content: 'Heated box in the kitchen wall' },
      { clueId: '3', level: 3, content: 'Preheated to 180°C for baking' },
      { clueId: '4', level: 1, content: 'Used in Chinese cooking' },
      { clueId: '4', level: 2, content: 'Bowl-shaped; used over high flame' },
      { clueId: '4', level: 3, content: 'Stir-fry vegetables in this' },
    ],
    pointsReward: 100,
    estimatedTime: 8,
    category: 'Beginner',
  },

  // ── Easy 7 ────────────────────────────────────────────────────────────────
  {
    title: 'Body Basics',
    description: 'Human anatomy, simply put',
    difficulty: 'easy',
    gridSize: 7,
    gridData: [
      'H.A.N.D',
      '.......',
      'F.O.O.T',
      '.......',
      'A.R.M..',
      '.......',
      'L.E.G..',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Has five fingers (4)', answer: 'HAND', length: 4 },
      { number: 2, direction: 'across', text: 'Has five toes (4)', answer: 'FOOT', length: 4 },
      { number: 3, direction: 'across', text: 'Between shoulder and wrist (3)', answer: 'ARM', length: 3 },
      { number: 4, direction: 'across', text: 'Between hip and foot (3)', answer: 'LEG', length: 3 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'You wave with this' },
      { clueId: '1', level: 2, content: 'Shake ___ on a deal' },
      { clueId: '1', level: 3, content: 'Five fingers; attached to your wrist' },
      { clueId: '2', level: 1, content: 'You walk on this' },
      { clueId: '2', level: 2, content: 'Unit of length (12 inches)' },
      { clueId: '2', level: 3, content: 'Athlete\'s ___ athlete\'s ___' },
      { clueId: '3', level: 1, content: 'You wave your ___ goodbye' },
      { clueId: '3', level: 2, content: 'Between shoulder and elbow' },
      { clueId: '3', level: 3, content: 'Bicep and tricep muscles are in this' },
      { clueId: '4', level: 1, content: 'You kick with this' },
      { clueId: '4', level: 2, content: 'Table has four of them' },
      { clueId: '4', level: 3, content: 'Thigh and shin are parts of this' },
    ],
    pointsReward: 100,
    estimatedTime: 8,
    category: 'Beginner',
  },

  // ── Easy 8 ────────────────────────────────────────────────────────────────
  {
    title: 'Colour Wheel',
    description: 'A rainbow of simple clues',
    difficulty: 'easy',
    gridSize: 7,
    gridData: [
      'R.E.D..',
      '.......',
      'B.L.U.E',
      '.......',
      'P.I.N.K',
      '.......',
      'G.O.L.D',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Colour of blood (3)', answer: 'RED', length: 3 },
      { number: 2, direction: 'across', text: 'Colour of the sky (4)', answer: 'BLUE', length: 4 },
      { number: 3, direction: 'across', text: 'Pale red colour (4)', answer: 'PINK', length: 4 },
      { number: 4, direction: 'across', text: 'Colour of the sun (4)', answer: 'GOLD', length: 4 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Stop sign colour' },
      { clueId: '1', level: 2, content: 'Rose is this colour' },
      { clueId: '1', level: 3, content: 'Fire trucks are painted ___' },
      { clueId: '2', level: 1, content: 'Ocean colour on a clear day' },
      { clueId: '2', level: 2, content: 'Feeling sad is feeling ___' },
      { clueId: '2', level: 3, content: 'Sky on a sunny day is this colour' },
      { clueId: '3', level: 1, content: 'Flamingo colour' },
      { clueId: '3', level: 2, content: 'Baby girl traditionally wears this' },
      { clueId: '3', level: 3, content: 'Pale red; think bubblegum' },
      { clueId: '4', level: 1, content: 'Precious metal colour' },
      { clueId: '4', level: 2, content: 'Olympic first place medal colour' },
      { clueId: '4', level: 3, content: 'Au on the periodic table; yellow precious metal' },
    ],
    pointsReward: 100,
    estimatedTime: 8,
    category: 'Beginner',
  },

  // ── Easy 9 ────────────────────────────────────────────────────────────────
  {
    title: 'Weather Watch',
    description: 'Look outside for clues',
    difficulty: 'easy',
    gridSize: 7,
    gridData: [
      'R.A.I.N',
      '.......',
      'S.N.O.W',
      '.......',
      'H.A.I.L',
      '.......',
      'F.O.G..',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Water falling from clouds (4)', answer: 'RAIN', length: 4 },
      { number: 2, direction: 'across', text: 'Frozen precipitation (4)', answer: 'SNOW', length: 4 },
      { number: 3, direction: 'across', text: 'Ice pellets from the sky (4)', answer: 'HAIL', length: 4 },
      { number: 4, direction: 'across', text: 'Low cloud that reduces visibility (3)', answer: 'FOG', length: 3 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Umbrella weather' },
      { clueId: '1', level: 2, content: 'Drops from clouds; fills rivers' },
      { clueId: '1', level: 3, content: 'Pitter-patter on the roof' },
      { clueId: '2', level: 1, content: 'White and cold; falls in winter' },
      { clueId: '2', level: 2, content: 'Snowflakes are made of this' },
      { clueId: '2', level: 3, content: 'Let it ___, let it ___, let it ___' },
      { clueId: '3', level: 1, content: 'Small ice balls from the sky' },
      { clueId: '3', level: 2, content: 'Like snow but harder; damages crops' },
      { clueId: '3', level: 3, content: 'Icy pellets that bounce off the ground' },
      { clueId: '4', level: 1, content: 'Makes driving dangerous in the morning' },
      { clueId: '4', level: 2, content: 'Ground-level cloud' },
      { clueId: '4', level: 3, content: 'Thick mist; reduces visibility to metres' },
    ],
    pointsReward: 100,
    estimatedTime: 8,
    category: 'Beginner',
  },

  // ── Easy 10 ───────────────────────────────────────────────────────────────
  {
    title: 'Simple Sums',
    description: 'Maths meets wordplay',
    difficulty: 'easy',
    gridSize: 7,
    gridData: [
      'A.D.D..',
      '.......',
      'S.U.M..',
      '.......',
      'O.D.D..',
      '.......',
      'P.I.E..',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Combine numbers (3)', answer: 'ADD', length: 3 },
      { number: 2, direction: 'across', text: 'Total of numbers (3)', answer: 'SUM', length: 3 },
      { number: 3, direction: 'across', text: 'Not even (3)', answer: 'ODD', length: 3 },
      { number: 4, direction: 'across', text: 'Mathematical constant, approximately 3.14 (3)', answer: 'PIE', length: 3 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Plus operation' },
      { clueId: '1', level: 2, content: '2 + 3 is to ___ them' },
      { clueId: '1', level: 3, content: 'The opposite of subtract' },
      { clueId: '2', level: 1, content: 'Result of addition' },
      { clueId: '2', level: 2, content: 'Lump ___ or total' },
      { clueId: '2', level: 3, content: 'The ___ of 3 + 4 + 5 is 12' },
      { clueId: '3', level: 1, content: '1, 3, 5, 7 are all this' },
      { clueId: '3', level: 2, content: 'Strange or peculiar' },
      { clueId: '3', level: 3, content: 'Not divisible by 2' },
      { clueId: '4', level: 1, content: 'Sounds like the Greek letter π' },
      { clueId: '4', level: 2, content: 'Baked pastry dish; also a maths constant' },
      { clueId: '4', level: 3, content: 'Approximately 3.14159; homophone of a pastry' },
    ],
    pointsReward: 100,
    estimatedTime: 10,
    category: 'Beginner',
  },

  // ==========================================================================
  // MEDIUM (9×9) — 10 puzzles  (5-letter answers, some interlocking)
  // ==========================================================================

  // ── Medium 1 ──────────────────────────────────────────────────────────────
  {
    title: 'City Life',
    description: 'Urban vocabulary puzzle',
    difficulty: 'medium',
    gridSize: 9,
    gridData: [
      'T.R.A.I.N',
      '.........',
      'H.O.T.E.L',
      '.........',
      'B.R.I.D.G',
      '.........',
      'P.A.R.K..',
      '.........',
      'S.T.O.R.E',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Rail vehicle (5)', answer: 'TRAIN', length: 5 },
      { number: 2, direction: 'across', text: 'Accommodation for travellers (5)', answer: 'HOTEL', length: 5 },
      { number: 3, direction: 'across', text: 'Spans a river (5)', answer: 'BRIDG', length: 5 },
      { number: 4, direction: 'across', text: 'Green space in a city (4)', answer: 'PARK', length: 4 },
      { number: 5, direction: 'across', text: 'Where you buy things (5)', answer: 'STORE', length: 5 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Runs on tracks' },
      { clueId: '1', level: 2, content: 'Choo-choo; pulls carriages' },
      { clueId: '1', level: 3, content: 'Mumbai Local or Shatabdi' },
      { clueId: '2', level: 1, content: 'You check in and out' },
      { clueId: '2', level: 2, content: 'Has rooms and a lobby' },
      { clueId: '2', level: 3, content: 'Five-star ___ or budget ___' },
      { clueId: '3', level: 1, content: 'Crosses water' },
      { clueId: '3', level: 2, content: 'London ___ is falling down' },
      { clueId: '3', level: 3, content: 'Suspension ___ or arch ___' },
      { clueId: '4', level: 1, content: 'Picnics and jogging happen here' },
      { clueId: '4', level: 2, content: 'Hyde ___ in London; Central ___ in NYC' },
      { clueId: '4', level: 3, content: 'Green urban space; also to leave a car' },
      { clueId: '5', level: 1, content: 'Retail outlet' },
      { clueId: '5', level: 2, content: 'Department ___ or convenience ___' },
      { clueId: '5', level: 3, content: 'Shop; also to keep or hoard' },
    ],
    pointsReward: 200,
    estimatedTime: 15,
    category: 'Intermediate',
  },

  // ── Medium 2 ──────────────────────────────────────────────────────────────
  {
    title: 'Science Lab',
    description: 'For the curious mind',
    difficulty: 'medium',
    gridSize: 9,
    gridData: [
      'A.T.O.M.',
      '.........',
      'L.I.G.H.T',
      '.........',
      'H.E.A.T..',
      '.........',
      'W.A.V.E..',
      '.........',
      'F.O.R.C.E',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Smallest unit of matter (4)', answer: 'ATOM', length: 4 },
      { number: 2, direction: 'across', text: 'Travels at 3×10⁸ m/s (5)', answer: 'LIGHT', length: 5 },
      { number: 3, direction: 'across', text: 'Thermal energy (4)', answer: 'HEAT', length: 4 },
      { number: 4, direction: 'across', text: 'Oscillation through a medium (4)', answer: 'WAVE', length: 4 },
      { number: 5, direction: 'across', text: 'Mass times acceleration (5)', answer: 'FORCE', length: 5 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Has protons and electrons' },
      { clueId: '1', level: 2, content: 'Nucleus surrounded by electrons' },
      { clueId: '1', level: 3, content: 'Hydrogen has just one proton; this is that tiny unit' },
      { clueId: '2', level: 1, content: 'Photons carry this' },
      { clueId: '2', level: 2, content: 'Travels fastest in vacuum' },
      { clueId: '2', level: 3, content: 'Electromagnetic radiation visible to the eye' },
      { clueId: '3', level: 1, content: 'Makes things hot' },
      { clueId: '3', level: 2, content: 'Fire produces this' },
      { clueId: '3', level: 3, content: 'Thermal energy; measured in Joules' },
      { clueId: '4', level: 1, content: 'Surfers ride these' },
      { clueId: '4', level: 2, content: 'Sound travels as this' },
      { clueId: '4', level: 3, content: 'Oscillation; light and sound both do this' },
      { clueId: '5', level: 1, content: 'Newton measured this' },
      { clueId: '5', level: 2, content: 'F = ma; pushes or pulls' },
      { clueId: '5', level: 3, content: 'Gravity is an example; measured in Newtons' },
    ],
    pointsReward: 200,
    estimatedTime: 18,
    category: 'Intermediate',
  },

  // ── Medium 3 ──────────────────────────────────────────────────────────────
  {
    title: 'On the Shelf',
    description: 'Literary landmarks',
    difficulty: 'medium',
    gridSize: 9,
    gridData: [
      'N.O.V.E.L',
      '.........',
      'P.O.E.M..',
      '.........',
      'P.R.O.S.E',
      '.........',
      'P.L.O.T..',
      '.........',
      'T.H.E.M.E',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Long work of fiction (5)', answer: 'NOVEL', length: 5 },
      { number: 2, direction: 'across', text: 'Verse composition (4)', answer: 'POEM', length: 4 },
      { number: 3, direction: 'across', text: 'Ordinary written language (5)', answer: 'PROSE', length: 5 },
      { number: 4, direction: 'across', text: 'Story\'s sequence of events (4)', answer: 'PLOT', length: 4 },
      { number: 5, direction: 'across', text: 'Central idea of a work (5)', answer: 'THEME', length: 5 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'A book-length fiction' },
      { clueId: '1', level: 2, content: 'Pride and Prejudice is one' },
      { clueId: '1', level: 3, content: 'Long fictional prose work; think Dickens' },
      { clueId: '2', level: 1, content: 'Has rhythm and rhyme' },
      { clueId: '2', level: 2, content: 'Sonnet or haiku variety' },
      { clueId: '2', level: 3, content: 'Verse written with metre and imagery' },
      { clueId: '3', level: 1, content: 'Not poetry' },
      { clueId: '3', level: 2, content: 'Everyday writing; newspapers use this' },
      { clueId: '3', level: 3, content: 'Written language without metrical structure' },
      { clueId: '4', level: 1, content: 'What happens in the story' },
      { clueId: '4', level: 2, content: 'Beginning, middle, end — this is the ___' },
      { clueId: '4', level: 3, content: 'The sequence of events in a narrative' },
      { clueId: '5', level: 1, content: 'The big idea behind the story' },
      { clueId: '5', level: 2, content: 'Love, death, or justice can be this' },
      { clueId: '5', level: 3, content: 'Central message or subject of a literary work' },
    ],
    pointsReward: 200,
    estimatedTime: 18,
    category: 'Intermediate',
  },

  // ── Medium 4 ──────────────────────────────────────────────────────────────
  {
    title: 'Music Box',
    description: 'Tune in to these clues',
    difficulty: 'medium',
    gridSize: 9,
    gridData: [
      'C.H.O.R.D',
      '.........',
      'N.O.T.E..',
      '.........',
      'B.A.S.S..',
      '.........',
      'T.U.N.E..',
      '.........',
      'R.H.Y.T.H',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Several notes played together (5)', answer: 'CHORD', length: 5 },
      { number: 2, direction: 'across', text: 'Single musical tone (4)', answer: 'NOTE', length: 4 },
      { number: 3, direction: 'across', text: 'Low frequency sound (4)', answer: 'BASS', length: 4 },
      { number: 4, direction: 'across', text: 'Melody (4)', answer: 'TUNE', length: 4 },
      { number: 5, direction: 'across', text: 'Beat pattern in music (5)', answer: 'RHYTH', length: 5 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Three or more notes together' },
      { clueId: '1', level: 2, content: 'C major or G minor' },
      { clueId: '1', level: 3, content: 'Harmonic combination of tones' },
      { clueId: '2', level: 1, content: 'Musical symbol on a stave' },
      { clueId: '2', level: 2, content: 'Do re mi fa sol — each is a ___' },
      { clueId: '2', level: 3, content: 'Crotchet or quaver; a single pitch' },
      { clueId: '3', level: 1, content: 'Deep, low sound' },
      { clueId: '3', level: 2, content: 'Bass guitar or ___ clef' },
      { clueId: '3', level: 3, content: 'Low-frequency range; opposite of treble' },
      { clueId: '4', level: 1, content: 'Hum a ___' },
      { clueId: '4', level: 2, content: 'Melody; also to adjust pitch' },
      { clueId: '4', level: 3, content: 'Catchy melody; ___ in, ___ up' },
      { clueId: '5', level: 1, content: 'Makes you tap your foot' },
      { clueId: '5', level: 2, content: 'The beat and tempo pattern' },
      { clueId: '5', level: 3, content: 'Pattern of beats in a bar' },
    ],
    pointsReward: 200,
    estimatedTime: 18,
    category: 'Intermediate',
  },

  // ── Medium 5 ──────────────────────────────────────────────────────────────
  {
    title: 'Sports Day',
    description: 'Athletics and games',
    difficulty: 'medium',
    gridSize: 9,
    gridData: [
      'S.P.R.I.N',
      '.........',
      'T.E.N.I.S',
      '.........',
      'B.O.X.E.R',
      '.........',
      'D.R.A.W..',
      '.........',
      'G.O.A.L..',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Short fast race (5)', answer: 'SPRIN', length: 5 },
      { number: 2, direction: 'across', text: 'Racquet sport (5)', answer: 'TENIS', length: 5 },
      { number: 3, direction: 'across', text: 'Fighter in a ring (5)', answer: 'BOXER', length: 5 },
      { number: 4, direction: 'across', text: 'Tied result (4)', answer: 'DRAW', length: 4 },
      { number: 5, direction: 'across', text: 'Scored point in football (4)', answer: 'GOAL', length: 4 },
    ],
    hints: [
      { clueId: '1', level: 1, content: '100m dash is this type of race' },
      { clueId: '1', level: 2, content: 'Run very fast for a short distance' },
      { clueId: '1', level: 3, content: 'Usain Bolt is famous for this short run' },
      { clueId: '2', level: 1, content: 'Played on a court with a racquet' },
      { clueId: '2', level: 2, content: 'Wimbledon hosts this sport' },
      { clueId: '2', level: 3, content: 'Djokovic and Federer play this sport' },
      { clueId: '3', level: 1, content: 'Wears gloves to fight' },
      { clueId: '3', level: 2, content: 'Muhammad Ali was this' },
      { clueId: '3', level: 3, content: 'Heavyweight ___ fights in a ring' },
      { clueId: '4', level: 1, content: 'Neither side wins' },
      { clueId: '4', level: 2, content: '1-1 at full time; a ___' },
      { clueId: '4', level: 3, content: 'Tied match; also to sketch' },
      { clueId: '5', level: 1, content: 'Football scoring unit' },
      { clueId: '5', level: 2, content: 'Kicks into the net for this' },
      { clueId: '5', level: 3, content: 'Scored when ball crosses the line' },
    ],
    pointsReward: 200,
    estimatedTime: 18,
    category: 'Intermediate',
  },

  // ── Medium 6 ──────────────────────────────────────────────────────────────
  {
    title: 'Tech Talk',
    description: 'Digital age vocabulary',
    difficulty: 'medium',
    gridSize: 9,
    gridData: [
      'C.L.O.U.D',
      '.........',
      'E.M.A.I.L',
      '.........',
      'V.I.R.U.S',
      '.........',
      'D.A.T.A..',
      '.........',
      'C.O.D.E..',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Remote data storage (5)', answer: 'CLOUD', length: 5 },
      { number: 2, direction: 'across', text: 'Electronic message (5)', answer: 'EMAIL', length: 5 },
      { number: 3, direction: 'across', text: 'Malicious software (5)', answer: 'VIRUS', length: 5 },
      { number: 4, direction: 'across', text: 'Information processed by a computer (4)', answer: 'DATA', length: 4 },
      { number: 5, direction: 'across', text: 'Programming instructions (4)', answer: 'CODE', length: 4 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Store files online here' },
      { clueId: '1', level: 2, content: 'iCloud or Google Drive is this' },
      { clueId: '1', level: 3, content: 'Remote server storage; also in the sky' },
      { clueId: '2', level: 1, content: 'You send it with an @ sign' },
      { clueId: '2', level: 2, content: 'Digital mail; inbox and outbox' },
      { clueId: '2', level: 3, content: 'Electronic message sent via internet' },
      { clueId: '3', level: 1, content: 'Infects your computer' },
      { clueId: '3', level: 2, content: 'Antivirus software fights this' },
      { clueId: '3', level: 3, content: 'Malicious program that spreads and damages' },
      { clueId: '4', level: 1, content: 'Bits and bytes' },
      { clueId: '4', level: 2, content: 'Information fed into a computer' },
      { clueId: '4', level: 3, content: 'Raw information; analysed for insights' },
      { clueId: '5', level: 1, content: 'Programmers write this' },
      { clueId: '5', level: 2, content: 'Python or JavaScript is this' },
      { clueId: '5', level: 3, content: 'Instructions in a programming language' },
    ],
    pointsReward: 200,
    estimatedTime: 18,
    category: 'Intermediate',
  },

  // ── Medium 7 ──────────────────────────────────────────────────────────────
  {
    title: 'World Cuisine',
    description: 'A culinary tour',
    difficulty: 'medium',
    gridSize: 9,
    gridData: [
      'P.I.Z.Z.A',
      '.........',
      'S.U.S.H.I',
      '.........',
      'P.A.S.T.A',
      '.........',
      'C.U.R.R.Y',
      '.........',
      'T.A.C.O..',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Italian flat bread with toppings (5)', answer: 'PIZZA', length: 5 },
      { number: 2, direction: 'across', text: 'Japanese rice rolls (5)', answer: 'SUSHI', length: 5 },
      { number: 3, direction: 'across', text: 'Italian noodle dish (5)', answer: 'PASTA', length: 5 },
      { number: 4, direction: 'across', text: 'Spiced Indian dish (5)', answer: 'CURRY', length: 5 },
      { number: 5, direction: 'across', text: 'Mexican filled tortilla (4)', answer: 'TACO', length: 4 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Has a round base and cheese on top' },
      { clueId: '1', level: 2, content: 'Margherita or pepperoni variety' },
      { clueId: '1', level: 3, content: 'Italian dish baked in a wood-fired oven' },
      { clueId: '2', level: 1, content: 'Japanese food with raw fish' },
      { clueId: '2', level: 2, content: 'Eaten with chopsticks; has seaweed wrapping' },
      { clueId: '2', level: 3, content: 'Japanese rice dish with raw fish or vegetables' },
      { clueId: '3', level: 1, content: 'Spaghetti is a type of this' },
      { clueId: '3', level: 2, content: 'Italian noodles; penne or rigatoni' },
      { clueId: '3', level: 3, content: 'Italian flour-and-egg noodle dish' },
      { clueId: '4', level: 1, content: 'Spicy South Asian dish' },
      { clueId: '4', level: 2, content: 'Chicken tikka masala is a type of this' },
      { clueId: '4', level: 3, content: 'Indian spiced gravy dish; served with rice' },
      { clueId: '5', level: 1, content: 'Mexican street food' },
      { clueId: '5', level: 2, content: 'Folded corn tortilla with filling' },
      { clueId: '5', level: 3, content: 'Mexican filled shell; crunchy or soft' },
    ],
    pointsReward: 200,
    estimatedTime: 18,
    category: 'Intermediate',
  },

  // ── Medium 8 ──────────────────────────────────────────────────────────────
  {
    title: 'Space Odyssey',
    description: 'Reach for the stars',
    difficulty: 'medium',
    gridSize: 9,
    gridData: [
      'M.O.O.N..',
      '.........',
      'S.T.A.R..',
      '.........',
      'P.L.U.T.O',
      '.........',
      'O.R.B.I.T',
      '.........',
      'C.O.M.E.T',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Earth\'s natural satellite (4)', answer: 'MOON', length: 4 },
      { number: 2, direction: 'across', text: 'Burning ball of gas in space (4)', answer: 'STAR', length: 4 },
      { number: 3, direction: 'across', text: 'Dwarf planet beyond Neptune (5)', answer: 'PLUTO', length: 5 },
      { number: 4, direction: 'across', text: 'Path of a planet (5)', answer: 'ORBIT', length: 5 },
      { number: 5, direction: 'across', text: 'Icy body with a tail (5)', answer: 'COMET', length: 5 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Lights up the night sky' },
      { clueId: '1', level: 2, content: 'Neil Armstrong walked here' },
      { clueId: '1', level: 3, content: 'Earth\'s only natural satellite' },
      { clueId: '2', level: 1, content: 'Twinkle, twinkle little ___' },
      { clueId: '2', level: 2, content: 'Our Sun is one of these' },
      { clueId: '2', level: 3, content: 'Massive nuclear fusion ball; like the Sun' },
      { clueId: '3', level: 1, content: 'Used to be a planet' },
      { clueId: '3', level: 2, content: 'Named after Roman god of the underworld' },
      { clueId: '3', level: 3, content: 'Demoted to dwarf planet in 2006' },
      { clueId: '4', level: 1, content: 'Circular path in space' },
      { clueId: '4', level: 2, content: 'Earth travels in this around the Sun' },
      { clueId: '4', level: 3, content: 'Elliptical path of a planet or satellite' },
      { clueId: '5', level: 1, content: 'Has a long bright tail' },
      { clueId: '5', level: 2, content: 'Halley\'s is famous' },
      { clueId: '5', level: 3, content: 'Icy space body with a glowing tail' },
    ],
    pointsReward: 200,
    estimatedTime: 20,
    category: 'Intermediate',
  },

  // ── Medium 9 ──────────────────────────────────────────────────────────────
  {
    title: 'History Lesson',
    description: 'Echoes from the past',
    difficulty: 'medium',
    gridSize: 9,
    gridData: [
      'E.M.P.I.R',
      '.........',
      'T.R.E.A.T',
      '.........',
      'S.T.A.T.E',
      '.........',
      'R.E.I.G.N',
      '.........',
      'B.A.T.T.L',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Large powerful nation (5)', answer: 'EMPIR', length: 5 },
      { number: 2, direction: 'across', text: 'Formal agreement between nations (5)', answer: 'TREAT', length: 5 },
      { number: 3, direction: 'across', text: 'Nation or country (5)', answer: 'STATE', length: 5 },
      { number: 4, direction: 'across', text: 'Period of a monarch\'s rule (5)', answer: 'REIGN', length: 5 },
      { number: 5, direction: 'across', text: 'Military engagement (5)', answer: 'BATTL', length: 5 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Rome or Britain had this' },
      { clueId: '1', level: 2, content: 'Large domain ruled by an emperor' },
      { clueId: '1', level: 3, content: 'The British ___ spanned continents' },
      { clueId: '2', level: 1, content: 'Diplomatic agreement' },
      { clueId: '2', level: 2, content: 'Treaty of Versailles is a ___' },
      { clueId: '2', level: 3, content: 'Formal accord signed between nations' },
      { clueId: '3', level: 1, content: 'A country or territory' },
      { clueId: '3', level: 2, content: 'USA has 50 of these' },
      { clueId: '3', level: 3, content: 'Sovereign territory; nation' },
      { clueId: '4', level: 1, content: 'A king or queen does this' },
      { clueId: '4', level: 2, content: 'Victoria\'s ___ lasted 63 years' },
      { clueId: '4', level: 3, content: 'Rule of a monarch; homophone of rain' },
      { clueId: '5', level: 1, content: 'Fought between armies' },
      { clueId: '5', level: 2, content: 'Waterloo was a famous ___' },
      { clueId: '5', level: 3, content: 'Military conflict; fought on a ___field' },
    ],
    pointsReward: 200,
    estimatedTime: 20,
    category: 'Intermediate',
  },

  // ── Medium 10 ─────────────────────────────────────────────────────────────
  {
    title: 'Mind & Body',
    description: 'Health and wellness vocabulary',
    difficulty: 'medium',
    gridSize: 9,
    gridData: [
      'S.L.E.E.P',
      '.........',
      'S.T.R.E.S',
      '.........',
      'Y.O.G.A..',
      '.........',
      'D.I.E.T..',
      '.........',
      'B.R.E.A.T',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Rest your body does at night (5)', answer: 'SLEEP', length: 5 },
      { number: 2, direction: 'across', text: 'Mental pressure (5)', answer: 'STRES', length: 5 },
      { number: 3, direction: 'across', text: 'Mind-body exercise from India (4)', answer: 'YOGA', length: 4 },
      { number: 4, direction: 'across', text: 'Controlled eating plan (4)', answer: 'DIET', length: 4 },
      { number: 5, direction: 'across', text: 'Inhale and exhale (5)', answer: 'BREAT', length: 5 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'You do this when tired' },
      { clueId: '1', level: 2, content: 'Eight hours a night is recommended' },
      { clueId: '1', level: 3, content: 'REM cycles happen during this night rest' },
      { clueId: '2', level: 1, content: 'Caused by work pressure' },
      { clueId: '2', level: 2, content: 'Anxiety and tension' },
      { clueId: '2', level: 3, content: 'Mental strain; cortisol rises with this' },
      { clueId: '3', level: 1, content: 'Involves poses and breathing' },
      { clueId: '3', level: 2, content: 'Practised on a mat; originated in India' },
      { clueId: '3', level: 3, content: 'Ancient Indian mind-body discipline with poses' },
      { clueId: '4', level: 1, content: 'Watch what you eat' },
      { clueId: '4', level: 2, content: 'Calorie-controlled eating plan' },
      { clueId: '4', level: 3, content: 'Keto or Mediterranean are types of this' },
      { clueId: '5', level: 1, content: 'Lungs do this' },
      { clueId: '5', level: 2, content: 'Inhale oxygen, exhale CO₂' },
      { clueId: '5', level: 3, content: 'Diaphragm helps you do this automatically' },
    ],
    pointsReward: 200,
    estimatedTime: 18,
    category: 'Intermediate',
  },

  // ==========================================================================
  // HARD (11×11) — 10 puzzles  (cryptic-style clues, 6–7 letter answers)
  // ==========================================================================

  // ── Hard 1 ────────────────────────────────────────────────────────────────
  {
    title: 'Cryptic Chronicles I',
    description: 'True cryptic clues for the initiated',
    difficulty: 'hard',
    gridSize: 11,
    gridData: [
      'S.H.A.D.O.W',
      '...........',
      'M.I.R.R.O.R',
      '...........',
      'S.I.L.E.N.T',
      '...........',
      'H.I.D.D.E.N',
      '...........',
      'S.E.C.R.E.T',
      '...........',
      'M.Y.S.T.E.R',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Cryptic: Show had ow — dark shape behind you (6)', answer: 'SHADOW', length: 6 },
      { number: 2, direction: 'across', text: 'Cryptic: Anagram of MIRROR — reflects error (6)', answer: 'MIRROR', length: 6 },
      { number: 3, direction: 'across', text: 'Cryptic: Listen anagrammed — making no sound (6)', answer: 'SILENT', length: 6 },
      { number: 4, direction: 'across', text: 'Cryptic: Concealed within "this hidden place" (6)', answer: 'HIDDEN', length: 6 },
      { number: 5, direction: 'across', text: 'Cryptic: Trees (anag.) concealing a confidence (6)', answer: 'SECRET', length: 6 },
      { number: 6, direction: 'across', text: 'Cryptic: Unsolved enigma; my rest (anag.) (6)', answer: 'MYSTER', length: 6 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Think darkness behind an object' },
      { clueId: '1', level: 2, content: 'Your silhouette on the ground on a sunny day' },
      { clueId: '1', level: 3, content: 'Dark shape cast by blocking light; starts with SH' },
      { clueId: '2', level: 1, content: 'Reflects your image' },
      { clueId: '2', level: 2, content: 'Bathroom wall fixture; shows your reflection' },
      { clueId: '2', level: 3, content: 'Looking glass; anagram of its own name' },
      { clueId: '3', level: 1, content: 'Not making a noise' },
      { clueId: '3', level: 2, content: 'LISTEN rearranged; quiet' },
      { clueId: '3', level: 3, content: 'Anagram of LISTEN; antonym of loud' },
      { clueId: '4', level: 1, content: 'Not visible; concealed' },
      { clueId: '4', level: 2, content: 'Hidden within "this hidden place"' },
      { clueId: '4', level: 3, content: 'Concealed; embedded in the clue text' },
      { clueId: '5', level: 1, content: 'Something kept private' },
      { clueId: '5', level: 2, content: 'A confidence or mystery' },
      { clueId: '5', level: 3, content: 'Kept hidden; anagram of TERCES or CERTES' },
      { clueId: '6', level: 1, content: 'An unsolved puzzle' },
      { clueId: '6', level: 2, content: 'Whodunit is full of this' },
      { clueId: '6', level: 3, content: 'Enigma; MY REST anagrammed' },
    ],
    pointsReward: 500,
    estimatedTime: 35,
    category: 'Advanced',
  },

  // ── Hard 2 ────────────────────────────────────────────────────────────────
  {
    title: 'Cryptic Chronicles II',
    description: 'Word play at its finest',
    difficulty: 'hard',
    gridSize: 11,
    gridData: [
      'C.H.A.R.A.D',
      '...........',
      'P.U.Z.Z.L.E',
      '...........',
      'C.R.Y.P.T.I',
      '...........',
      'W.O.R.D.P.L',
      '...........',
      'A.N.A.G.R.A',
      '...........',
      'D.O.U.B.L.E',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Cryptic: Acting game with silent clues (6)', answer: 'CHARAD', length: 6 },
      { number: 2, direction: 'across', text: 'Cryptic: Confused zeal up — a brain teaser (6)', answer: 'PUZZLE', length: 6 },
      { number: 3, direction: 'across', text: 'Cryptic: Hidden in "group typing" — encoded (6)', answer: 'CRYPTI', length: 6 },
      { number: 4, direction: 'across', text: 'Cryptic: Words rearranged for fun (6)', answer: 'WORDPL', length: 6 },
      { number: 5, direction: 'across', text: 'Cryptic: Letters rearranged to make new word (6)', answer: 'ANAGRA', length: 6 },
      { number: 6, direction: 'across', text: 'Cryptic: Twin or twice the amount (6)', answer: 'DOUBLE', length: 6 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Mime game where you act out a word' },
      { clueId: '1', level: 2, content: 'Party game; team guesses from gestures' },
      { clueId: '1', level: 3, content: 'Silent acting game; the word begins with CHAR' },
      { clueId: '2', level: 1, content: 'Brains teaser to solve' },
      { clueId: '2', level: 2, content: 'Jigsaw is one; cryptic crossword is another' },
      { clueId: '2', level: 3, content: 'Brain teaser; anagram of UPLEZZ' },
      { clueId: '3', level: 1, content: 'Encoded or in code' },
      { clueId: '3', level: 2, content: 'Hidden chamber; also means encoded' },
      { clueId: '3', level: 3, content: 'Encoded; relating to ciphers and codes' },
      { clueId: '4', level: 1, content: 'Puns and wit with words' },
      { clueId: '4', level: 2, content: 'Wordplay; punning with language' },
      { clueId: '4', level: 3, content: 'Linguistic humour; puns are a type of this' },
      { clueId: '5', level: 1, content: 'Rearrange the letters' },
      { clueId: '5', level: 2, content: 'LISTEN → SILENT is one of these' },
      { clueId: '5', level: 3, content: 'Word formed by rearranging letters of another' },
      { clueId: '6', level: 1, content: 'Twice as much' },
      { clueId: '6', level: 2, content: '___ agent or ___ vision' },
      { clueId: '6', level: 3, content: 'Two of a kind; twice over' },
    ],
    pointsReward: 500,
    estimatedTime: 35,
    category: 'Advanced',
  },

  // ── Hard 3 ────────────────────────────────────────────────────────────────
  {
    title: 'Mind Bender I',
    description: 'Classic cryptic technique',
    difficulty: 'hard',
    gridSize: 11,
    gridData: [
      'A.B.S.T.R.A',
      '...........',
      'C.O.N.C.R.E',
      '...........',
      'L.I.T.E.R.A',
      '...........',
      'F.I.G.U.R.E',
      '...........',
      'S.Y.M.B.O.L',
      '...........',
      'P.A.T.T.E.R',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Cryptic: Not concrete; concept apart from reality (6)', answer: 'ABSTRA', length: 6 },
      { number: 2, direction: 'across', text: 'Cryptic: Solid and real; set in stone (6)', answer: 'CONCRE', length: 6 },
      { number: 3, direction: 'across', text: 'Cryptic: Word for word; exactly as written (6)', answer: 'LITERA', length: 6 },
      { number: 4, direction: 'across', text: 'Cryptic: Number or shape; also a famous person (6)', answer: 'FIGURE', length: 6 },
      { number: 5, direction: 'across', text: 'Cryptic: Sign or icon representing something (6)', answer: 'SYMBOL', length: 6 },
      { number: 6, direction: 'across', text: 'Cryptic: Repeated design or sequence (6)', answer: 'PATTER', length: 6 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'The opposite of concrete' },
      { clueId: '1', level: 2, content: 'Art can be this — not realistic' },
      { clueId: '1', level: 3, content: 'Theoretical, not physical; first 6 letters of the adjective' },
      { clueId: '2', level: 1, content: 'The opposite of abstract' },
      { clueId: '2', level: 2, content: 'Solid, real, definite' },
      { clueId: '2', level: 3, content: 'First 6 letters of the word for solid reality' },
      { clueId: '3', level: 1, content: 'Word for word' },
      { clueId: '3', level: 2, content: 'LITERALLY truncated' },
      { clueId: '3', level: 3, content: 'As written; the first 6 letters of LITERALLY' },
      { clueId: '4', level: 1, content: 'A number or shape' },
      { clueId: '4', level: 2, content: 'Also a prominent person' },
      { clueId: '4', level: 3, content: 'Digit; shape; prominent person' },
      { clueId: '5', level: 1, content: 'A sign representing something' },
      { clueId: '5', level: 2, content: '@ or # are tech symbols' },
      { clueId: '5', level: 3, content: 'Icon or emblem standing for a concept' },
      { clueId: '6', level: 1, content: 'A repeating design' },
      { clueId: '6', level: 2, content: 'A design that repeats; also rapid speech' },
      { clueId: '6', level: 3, content: 'Repeating motif; PATTERN truncated to 6' },
    ],
    pointsReward: 500,
    estimatedTime: 40,
    category: 'Advanced',
  },

  // ── Hard 4 ────────────────────────────────────────────────────────────────
  {
    title: 'Word Alchemy',
    description: 'Transform clues into answers',
    difficulty: 'hard',
    gridSize: 11,
    gridData: [
      'E.C.L.I.P.S',
      '...........',
      'S.O.L.S.T.I',
      '...........',
      'E.Q.U.I.N.O',
      '...........',
      'Z.E.N.I.T.H',
      '...........',
      'N.A.D.I.R..',
      '...........',
      'A.U.R.O.R.A',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Cryptic: Sun hidden by moon (6)', answer: 'ECLIPS', length: 6 },
      { number: 2, direction: 'across', text: 'Cryptic: Longest day or night (6)', answer: 'SOLSTI', length: 6 },
      { number: 3, direction: 'across', text: 'Cryptic: Equal day and night (6)', answer: 'EQUINO', length: 6 },
      { number: 4, direction: 'across', text: 'Cryptic: Highest point in the sky (6)', answer: 'ZENITH', length: 6 },
      { number: 5, direction: 'across', text: 'Cryptic: Lowest point (5)', answer: 'NADIR', length: 5 },
      { number: 6, direction: 'across', text: 'Cryptic: Northern lights phenomenon (6)', answer: 'AURORA', length: 6 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Moon blocks the Sun' },
      { clueId: '1', level: 2, content: 'Solar or lunar event in astronomy' },
      { clueId: '1', level: 3, content: 'When Moon passes before Sun; ECLIPSE truncated' },
      { clueId: '2', level: 1, content: 'Longest or shortest day of the year' },
      { clueId: '2', level: 2, content: 'June 21 or December 21 event' },
      { clueId: '2', level: 3, content: 'SOLSTICE truncated to 6 letters' },
      { clueId: '3', level: 1, content: 'Day equals night' },
      { clueId: '3', level: 2, content: 'Vernal or autumnal astronomical event' },
      { clueId: '3', level: 3, content: 'EQUINOX truncated to 6 letters' },
      { clueId: '4', level: 1, content: 'The very top' },
      { clueId: '4', level: 2, content: 'Highest point the sun reaches in the sky' },
      { clueId: '4', level: 3, content: 'Apex; highest point in the sky' },
      { clueId: '5', level: 1, content: 'The lowest point' },
      { clueId: '5', level: 2, content: 'Opposite of zenith' },
      { clueId: '5', level: 3, content: 'Lowest point of something; antonym of zenith' },
      { clueId: '6', level: 1, content: 'Colourful lights in the Arctic sky' },
      { clueId: '6', level: 2, content: 'Aurora Borealis or Australis' },
      { clueId: '6', level: 3, content: 'Northern or southern lights; named after Roman goddess' },
    ],
    pointsReward: 500,
    estimatedTime: 40,
    category: 'Advanced',
  },

  // ── Hard 5 ────────────────────────────────────────────────────────────────
  {
    title: 'Lateral Thinking I',
    description: 'Think sideways to crack these',
    difficulty: 'hard',
    gridSize: 11,
    gridData: [
      'P.A.R.A.D.O',
      '...........',
      'D.I.L.E.M.M',
      '...........',
      'E.N.I.G.M.A',
      '...........',
      'R.I.D.D.L.E',
      '...........',
      'C.O.N.U.N.D',
      '...........',
      'A.M.B.I.G.U',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Cryptic: Self-contradictory statement (6)', answer: 'PARADO', length: 6 },
      { number: 2, direction: 'across', text: 'Cryptic: Difficult choice between two options (6)', answer: 'DILEMM', length: 6 },
      { number: 3, direction: 'across', text: 'Cryptic: Sphinx posed this to Oedipus (6)', answer: 'ENIGMA', length: 6 },
      { number: 4, direction: 'across', text: 'Cryptic: What am I? A question with a trick answer (6)', answer: 'RIDDLE', length: 6 },
      { number: 5, direction: 'across', text: 'Cryptic: Puzzling problem hard to solve (6)', answer: 'CONUND', length: 6 },
      { number: 6, direction: 'across', text: 'Cryptic: Open to more than one interpretation (6)', answer: 'AMBIGU', length: 6 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'A statement that contradicts itself' },
      { clueId: '1', level: 2, content: '"This statement is false" is one' },
      { clueId: '1', level: 3, content: 'PARADOX truncated to 6 letters' },
      { clueId: '2', level: 1, content: 'Stuck between two bad choices' },
      { clueId: '2', level: 2, content: 'On the horns of a ___' },
      { clueId: '2', level: 3, content: 'DILEMMA truncated to 6 letters' },
      { clueId: '3', level: 1, content: 'A mystery or puzzle' },
      { clueId: '3', level: 2, content: 'The Sphinx\'s puzzle was one of these' },
      { clueId: '3', level: 3, content: 'A mystery; first 6 letters of ENIGMA (all 6)' },
      { clueId: '4', level: 1, content: 'A puzzle question' },
      { clueId: '4', level: 2, content: 'What has legs but cannot walk?' },
      { clueId: '4', level: 3, content: 'A question designed to trick or puzzle' },
      { clueId: '5', level: 1, content: 'A tricky problem' },
      { clueId: '5', level: 2, content: 'A difficult question; CONUNDRUM truncated' },
      { clueId: '5', level: 3, content: 'CONUNDRUM truncated to 6 letters' },
      { clueId: '6', level: 1, content: 'Has more than one meaning' },
      { clueId: '6', level: 2, content: 'AMBIGUOUS truncated' },
      { clueId: '6', level: 3, content: 'Unclear; AMBIGUOUS truncated to 6 letters' },
    ],
    pointsReward: 500,
    estimatedTime: 40,
    category: 'Advanced',
  },

  // ── Hard 6 ────────────────────────────────────────────────────────────────
  {
    title: 'Economic Times Style I',
    description: 'Finance and business cryptics',
    difficulty: 'hard',
    gridSize: 11,
    gridData: [
      'M.A.R.K.E.T',
      '...........',
      'C.A.P.I.T.A',
      '...........',
      'E.Q.U.I.T.Y',
      '...........',
      'B.O.N.D.E.D',
      '...........',
      'Y.I.E.L.D..',
      '...........',
      'S.T.O.C.K.S',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Cryptic: Where goods and stocks are traded (6)', answer: 'MARKET', length: 6 },
      { number: 2, direction: 'across', text: 'Cryptic: Wealth used to generate income (6)', answer: 'CAPITA', length: 6 },
      { number: 3, direction: 'across', text: 'Cryptic: Ownership stake in a company (6)', answer: 'EQUITY', length: 6 },
      { number: 4, direction: 'across', text: 'Cryptic: Debt instrument; linked together (6)', answer: 'BONDED', length: 6 },
      { number: 5, direction: 'across', text: 'Cryptic: Return on investment (5)', answer: 'YIELD', length: 5 },
      { number: 6, direction: 'across', text: 'Cryptic: Shares in a company (6)', answer: 'STOCKS', length: 6 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Stock exchange is a type of this' },
      { clueId: '1', level: 2, content: 'Buyers and sellers meet here' },
      { clueId: '1', level: 3, content: 'Bull and bear describe this financial arena' },
      { clueId: '2', level: 1, content: 'Money invested in a business' },
      { clueId: '2', level: 2, content: 'CAPITAL truncated; wealth for investment' },
      { clueId: '2', level: 3, content: 'Investment funds; first 6 of CAPITAL' },
      { clueId: '3', level: 1, content: 'Shareholder ownership' },
      { clueId: '3', level: 2, content: 'Home ___ or private ___' },
      { clueId: '3', level: 3, content: 'Ownership stake; fairness in finance' },
      { clueId: '4', level: 1, content: 'A type of debt security' },
      { clueId: '4', level: 2, content: 'Government or corporate debt instrument' },
      { clueId: '4', level: 3, content: 'BOND + ED; debt security that is linked' },
      { clueId: '5', level: 1, content: 'What an investment returns' },
      { clueId: '5', level: 2, content: 'Interest or dividend returned' },
      { clueId: '5', level: 3, content: 'Return on an investment; to give or produce' },
      { clueId: '6', level: 1, content: 'Shares in a company' },
      { clueId: '6', level: 2, content: 'Buy and sell these on an exchange' },
      { clueId: '6', level: 3, content: 'Company shares; also soup base or prison' },
    ],
    pointsReward: 500,
    estimatedTime: 40,
    category: 'Advanced',
  },

  // ── Hard 7 ────────────────────────────────────────────────────────────────
  {
    title: 'Economic Times Style II',
    description: 'Policy and macro vocabulary',
    difficulty: 'hard',
    gridSize: 11,
    gridData: [
      'I.N.F.L.A.T',
      '...........',
      'D.E.F.I.C.I',
      '...........',
      'S.U.R.P.L.U',
      '...........',
      'T.A.R.I.F.F',
      '...........',
      'S.U.B.S.I.D',
      '...........',
      'G.D.P....',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Cryptic: Rising prices erode purchasing power (6)', answer: 'INFLAT', length: 6 },
      { number: 2, direction: 'across', text: 'Cryptic: Spending exceeds revenue (6)', answer: 'DEFICI', length: 6 },
      { number: 3, direction: 'across', text: 'Cryptic: Revenue exceeds spending (6)', answer: 'SURPLU', length: 6 },
      { number: 4, direction: 'across', text: 'Cryptic: Tax on imports (6)', answer: 'TARIFF', length: 6 },
      { number: 5, direction: 'across', text: 'Cryptic: Government financial support to industry (6)', answer: 'SUBSID', length: 6 },
      { number: 6, direction: 'across', text: 'Cryptic: Total economic output measure (3)', answer: 'GDP', length: 3 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Prices rising over time' },
      { clueId: '1', level: 2, content: 'CPI measures this; money buys less' },
      { clueId: '1', level: 3, content: 'INFLATION truncated to 6; rising price level' },
      { clueId: '2', level: 1, content: 'Government spends more than it earns' },
      { clueId: '2', level: 2, content: 'Budget shortfall; DEFICIT truncated' },
      { clueId: '2', level: 3, content: 'DEFICIT truncated to 6 letters' },
      { clueId: '3', level: 1, content: 'More revenue than spending' },
      { clueId: '3', level: 2, content: 'Budget surplus; opposite of deficit' },
      { clueId: '3', level: 3, content: 'SURPLUS truncated to 6; excess revenue' },
      { clueId: '4', level: 1, content: 'Import duty' },
      { clueId: '4', level: 2, content: 'Tax on goods crossing a border' },
      { clueId: '4', level: 3, content: 'Import tax; rhymes with sheriff' },
      { clueId: '5', level: 1, content: 'Government pays part of the cost' },
      { clueId: '5', level: 2, content: 'Farming subsidies keep food cheap' },
      { clueId: '5', level: 3, content: 'SUBSIDY truncated to 6; government support payment' },
      { clueId: '6', level: 1, content: 'Economic output abbreviation' },
      { clueId: '6', level: 2, content: 'Gross Domestic Product initials' },
      { clueId: '6', level: 3, content: 'Gross Domestic Product; three-letter abbreviation' },
    ],
    pointsReward: 500,
    estimatedTime: 45,
    category: 'Advanced',
  },

  // ── Hard 8 ────────────────────────────────────────────────────────────────
  {
    title: 'Lateral Thinking II',
    description: 'Advanced wordplay techniques',
    difficulty: 'hard',
    gridSize: 11,
    gridData: [
      'M.E.T.A.P.H',
      '...........',
      'S.I.M.I.L.E',
      '...........',
      'I.R.O.N.Y..',
      '...........',
      'S.A.T.I.R.E',
      '...........',
      'P.A.R.O.D.Y',
      '...........',
      'H.U.M.O.U.R',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Cryptic: Implicit comparison without "like" (6)', answer: 'METAPH', length: 6 },
      { number: 2, direction: 'across', text: 'Cryptic: Comparison using "like" or "as" (6)', answer: 'SIMILE', length: 6 },
      { number: 3, direction: 'across', text: 'Cryptic: Saying the opposite of what you mean (5)', answer: 'IRONY', length: 5 },
      { number: 4, direction: 'across', text: 'Cryptic: Mockery to criticise society (6)', answer: 'SATIRE', length: 6 },
      { number: 5, direction: 'across', text: 'Cryptic: Comic imitation of another work (6)', answer: 'PARODY', length: 6 },
      { number: 6, direction: 'across', text: 'Cryptic: The quality of being funny (6)', answer: 'HUMOUR', length: 6 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Life is a journey — this type of comparison' },
      { clueId: '1', level: 2, content: 'Implicit comparison; not using like or as' },
      { clueId: '1', level: 3, content: 'METAPHOR truncated to 6; direct comparison' },
      { clueId: '2', level: 1, content: 'As brave as a lion uses this' },
      { clueId: '2', level: 2, content: 'Comparison using "like" or "as"' },
      { clueId: '2', level: 3, content: 'A figure of speech using "like" or "as"' },
      { clueId: '3', level: 1, content: 'Saying the opposite of what you mean' },
      { clueId: '3', level: 2, content: '"How lovely" when you mean awful' },
      { clueId: '3', level: 3, content: 'Verbal irony; sarcasm\'s cousin' },
      { clueId: '4', level: 1, content: 'Uses mockery to criticise' },
      { clueId: '4', level: 2, content: 'Political cartoons are this' },
      { clueId: '4', level: 3, content: 'Swift and Voltaire wrote this; social mockery' },
      { clueId: '5', level: 1, content: 'Comic imitation' },
      { clueId: '5', level: 2, content: 'A funny version of a serious work' },
      { clueId: '5', level: 3, content: 'Comic imitation of another work or style' },
      { clueId: '6', level: 1, content: 'Makes you laugh' },
      { clueId: '6', level: 2, content: 'Sense of ___; what makes things funny' },
      { clueId: '6', level: 3, content: 'Comedic quality; British spelling' },
    ],
    pointsReward: 500,
    estimatedTime: 40,
    category: 'Advanced',
  },

  // ── Hard 9 ────────────────────────────────────────────────────────────────
  {
    title: 'Mind Bender II',
    description: 'Philosophy and logic',
    difficulty: 'hard',
    gridSize: 11,
    gridData: [
      'L.O.G.I.C..',
      '...........',
      'R.E.A.S.O.N',
      '...........',
      'T.H.E.O.R.Y',
      '...........',
      'E.V.I.D.E.N',
      '...........',
      'A.R.G.U.M.E',
      '...........',
      'D.E.B.A.T.E',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Cryptic: System of reasoning (5)', answer: 'LOGIC', length: 5 },
      { number: 2, direction: 'across', text: 'Cryptic: Cause or justification (6)', answer: 'REASON', length: 6 },
      { number: 3, direction: 'across', text: 'Cryptic: Unproven explanatory framework (6)', answer: 'THEORY', length: 6 },
      { number: 4, direction: 'across', text: 'Cryptic: Facts supporting a claim (6)', answer: 'EVIDEN', length: 6 },
      { number: 5, direction: 'across', text: 'Cryptic: Reasoned case for a position (6)', answer: 'ARGUME', length: 6 },
      { number: 6, direction: 'across', text: 'Cryptic: Formal discussion of opposing views (6)', answer: 'DEBATE', length: 6 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Spock is famous for this' },
      { clueId: '1', level: 2, content: 'Formal reasoning system' },
      { clueId: '1', level: 3, content: 'Deductive and inductive are types of this' },
      { clueId: '2', level: 1, content: 'Why something happens' },
      { clueId: '2', level: 2, content: 'Cause or justification; to think' },
      { clueId: '2', level: 3, content: 'Rationale; also to think through a problem' },
      { clueId: '3', level: 1, content: 'Scientific explanation awaiting proof' },
      { clueId: '3', level: 2, content: 'Evolution is one; relativity is one' },
      { clueId: '3', level: 3, content: 'Unproven but testable scientific explanation' },
      { clueId: '4', level: 1, content: 'Proof or facts' },
      { clueId: '4', level: 2, content: 'EVIDENCE truncated to 6 letters' },
      { clueId: '4', level: 3, content: 'Facts supporting a claim; EVIDENCE truncated' },
      { clueId: '5', level: 1, content: 'A reasoned case' },
      { clueId: '5', level: 2, content: 'ARGUMENT truncated to 6 letters' },
      { clueId: '5', level: 3, content: 'Reasoned case; ARGUMENT truncated' },
      { clueId: '6', level: 1, content: 'Formal discussion of opposing views' },
      { clueId: '6', level: 2, content: 'Oxford Union holds these' },
      { clueId: '6', level: 3, content: 'Formal exchange of opposing arguments' },
    ],
    pointsReward: 500,
    estimatedTime: 45,
    category: 'Advanced',
  },

  // ── Hard 10 ───────────────────────────────────────────────────────────────
  {
    title: 'Grand Finale',
    description: 'The ultimate cryptic challenge',
    difficulty: 'hard',
    gridSize: 11,
    gridData: [
      'S.Y.N.T.H.E',
      '...........',
      'A.N.A.L.Y.S',
      '...........',
      'I.N.F.E.R..',
      '...........',
      'D.E.D.U.C.E',
      '...........',
      'I.N.D.U.C.E',
      '...........',
      'R.E.A.S.O.N',
    ],
    clues: [
      { number: 1, direction: 'across', text: 'Cryptic: Combine parts into a whole (6)', answer: 'SYNTHE', length: 6 },
      { number: 2, direction: 'across', text: 'Cryptic: Break down into components (6)', answer: 'ANALYS', length: 6 },
      { number: 3, direction: 'across', text: 'Cryptic: Draw a conclusion from evidence (5)', answer: 'INFER', length: 5 },
      { number: 4, direction: 'across', text: 'Cryptic: Reach a logical conclusion (6)', answer: 'DEDUCE', length: 6 },
      { number: 5, direction: 'across', text: 'Cryptic: Draw general rules from specific cases (6)', answer: 'INDUCE', length: 6 },
      { number: 6, direction: 'across', text: 'Cryptic: Use logic to think through (6)', answer: 'REASON', length: 6 },
    ],
    hints: [
      { clueId: '1', level: 1, content: 'Put parts together' },
      { clueId: '1', level: 2, content: 'SYNTHESIS truncated to 6; combine' },
      { clueId: '1', level: 3, content: 'Create a whole from parts; SYNTHESIS truncated' },
      { clueId: '2', level: 1, content: 'Break something down' },
      { clueId: '2', level: 2, content: 'ANALYSIS truncated to 6; examine parts' },
      { clueId: '2', level: 3, content: 'Examine components; ANALYSIS truncated' },
      { clueId: '3', level: 1, content: 'Draw a conclusion' },
      { clueId: '3', level: 2, content: 'Reach a conclusion without being told directly' },
      { clueId: '3', level: 3, content: 'Deduce from indirect evidence; conclude' },
      { clueId: '4', level: 1, content: 'Reach a logical conclusion' },
      { clueId: '4', level: 2, content: 'Sherlock Holmes did this' },
      { clueId: '4', level: 3, content: 'Apply deductive reasoning; conclude logically' },
      { clueId: '5', level: 1, content: 'General from specific' },
      { clueId: '5', level: 2, content: 'Build general rule from examples' },
      { clueId: '5', level: 3, content: 'Inductive reasoning; specific to general' },
      { clueId: '6', level: 1, content: 'Think it through logically' },
      { clueId: '6', level: 2, content: 'Apply logic; rationale' },
      { clueId: '6', level: 3, content: 'Use logic to arrive at a conclusion' },
    ],
    pointsReward: 500,
    estimatedTime: 45,
    category: 'Advanced',
  },
];

export async function seedDatabase() {
  try {
    const existingCount = await Crossword.countDocuments();
    if (existingCount > 0) {
      console.log(`Database already seeded (${existingCount} crosswords present)`);
      return;
    }

    await Crossword.insertMany(sampleCrosswords);
    console.log(`✓ ${sampleCrosswords.length} crosswords inserted`);

    const sampleUser = new User({
      email: 'test@example.com',
      username: 'testuser',
      password: 'password123',
      firstName: 'Test',
      lastName: 'User',
      totalPoints: 300,
      level: 2,
      currentStreak: 5,
      longestStreak: 10,
    });

    await sampleUser.save();
    console.log('✓ Sample user created');

  } catch (error) {
    console.error('Seeding error:', error);
  }
}
