/**
 * Seed word list for learncrossword.in
 * ~180 words suitable for British cryptic crosswords (Chambers/Collins standard)
 * Replace/extend this with a full import from the user's generated word list JSON.
 */

export interface WordEntry {
  word: string;
  length: number;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  pos: 'noun' | 'verb' | 'adjective' | 'adverb';
}

export const WORD_LIST: WordEntry[] = [
  // ── 3-letter ── beginner
  { word: 'ACE', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'AGE', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'AID', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'AIM', length: 3, difficulty: 'beginner', pos: 'verb' },
  { word: 'AIR', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'ARC', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'AXE', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'BAY', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'BOW', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'CAP', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'COB', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'CUP', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'DIM', length: 3, difficulty: 'beginner', pos: 'adjective' },
  { word: 'DIP', length: 3, difficulty: 'beginner', pos: 'verb' },
  { word: 'EAR', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'EGG', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'ELM', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'EWE', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'FIG', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'GEM', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'JAM', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'JET', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'JOY', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'LAW', length: 3, difficulty: 'beginner', pos: 'noun' },
  { word: 'LEG', length: 3, difficulty: 'beginner', pos: 'noun' },

  // ── 4-letter ── beginner
  { word: 'ARCH', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'BALL', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'BARN', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'BEAR', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'BELL', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'BIRD', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'BOAT', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'BOLD', length: 4, difficulty: 'beginner', pos: 'adjective' },
  { word: 'BOOK', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'CAVE', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'CLAY', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'CLUE', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'COAL', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'CORN', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'CRAB', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'DAWN', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'DESK', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'DISH', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'DOME', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'DRUM', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'DUSK', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'EARL', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'FACE', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'FAIR', length: 4, difficulty: 'beginner', pos: 'adjective' },
  { word: 'FARM', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'FEAR', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'FEEL', length: 4, difficulty: 'beginner', pos: 'verb' },
  { word: 'FILE', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'FISH', length: 4, difficulty: 'beginner', pos: 'noun' },
  { word: 'FOAM', length: 4, difficulty: 'beginner', pos: 'noun' },

  // ── 4-letter ── intermediate
  { word: 'GALE', length: 4, difficulty: 'intermediate', pos: 'noun' },
  { word: 'GERM', length: 4, difficulty: 'intermediate', pos: 'noun' },
  { word: 'GRIM', length: 4, difficulty: 'intermediate', pos: 'adjective' },
  { word: 'GULF', length: 4, difficulty: 'intermediate', pos: 'noun' },
  { word: 'HARE', length: 4, difficulty: 'intermediate', pos: 'noun' },
  { word: 'HARP', length: 4, difficulty: 'intermediate', pos: 'noun' },
  { word: 'HAWK', length: 4, difficulty: 'intermediate', pos: 'noun' },
  { word: 'HELM', length: 4, difficulty: 'intermediate', pos: 'noun' },
  { word: 'HEMP', length: 4, difficulty: 'intermediate', pos: 'noun' },
  { word: 'HERO', length: 4, difficulty: 'intermediate', pos: 'noun' },

  // ── 5-letter ── beginner
  { word: 'ANGEL', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'APPLE', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'ARENA', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'AUDIO', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'BEACH', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'BRAVE', length: 5, difficulty: 'beginner', pos: 'adjective' },
  { word: 'BREAD', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'BRIDE', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'BROOK', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'BRUSH', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'BUILD', length: 5, difficulty: 'beginner', pos: 'verb' },
  { word: 'CABIN', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'CHAIN', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'CHALK', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'CHARM', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'CHESS', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'CHILD', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'CHINA', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'CHOIR', length: 5, difficulty: 'beginner', pos: 'noun' },
  { word: 'CRAFT', length: 5, difficulty: 'beginner', pos: 'noun' },

  // ── 5-letter ── intermediate
  { word: 'BRASH', length: 5, difficulty: 'intermediate', pos: 'adjective' },
  { word: 'CREED', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'CROWN', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'DUNCE', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'ENVOY', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'EPICS', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'EVOKE', length: 5, difficulty: 'intermediate', pos: 'verb' },
  { word: 'EXERT', length: 5, difficulty: 'intermediate', pos: 'verb' },
  { word: 'EXPEL', length: 5, difficulty: 'intermediate', pos: 'verb' },
  { word: 'FABLE', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'FARCE', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'FEAST', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'FIBRE', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'FLANK', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'FLARE', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'FLASK', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'FLESH', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'FLOOR', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'FLOSS', length: 5, difficulty: 'intermediate', pos: 'noun' },
  { word: 'FLUTE', length: 5, difficulty: 'intermediate', pos: 'noun' },

  // ── 6-letter ── intermediate
  { word: 'ABLAZE', length: 6, difficulty: 'intermediate', pos: 'adjective' },
  { word: 'ANTICS', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'ARMOUR', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'BEACON', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'BELFRY', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'BITTER', length: 6, difficulty: 'intermediate', pos: 'adjective' },
  { word: 'BLAZER', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'BONNET', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'BORDER', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'BOTHER', length: 6, difficulty: 'intermediate', pos: 'verb' },
  { word: 'BOUNCE', length: 6, difficulty: 'intermediate', pos: 'verb' },
  { word: 'BREEZE', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'BRIDGE', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'BRIGHT', length: 6, difficulty: 'intermediate', pos: 'adjective' },
  { word: 'BROOCH', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'BUFFET', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'BURDEN', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'CASKET', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'CAVERN', length: 6, difficulty: 'intermediate', pos: 'noun' },
  { word: 'CENSOR', length: 6, difficulty: 'intermediate', pos: 'verb' },

  // ── 6-letter ── advanced
  { word: 'ABLOOM', length: 6, difficulty: 'advanced', pos: 'adjective' },
  { word: 'ABOUND', length: 6, difficulty: 'advanced', pos: 'verb' },
  { word: 'ABRUPT', length: 6, difficulty: 'advanced', pos: 'adjective' },
  { word: 'ARDENT', length: 6, difficulty: 'advanced', pos: 'adjective' },
  { word: 'ARTFUL', length: 6, difficulty: 'advanced', pos: 'adjective' },
  { word: 'ASTUTE', length: 6, difficulty: 'advanced', pos: 'adjective' },
  { word: 'AUGMENT', length: 7, difficulty: 'advanced', pos: 'verb' },

  // ── 7-letter ── intermediate
  { word: 'ACCRUED', length: 7, difficulty: 'intermediate', pos: 'verb' },
  { word: 'ADMIRAL', length: 7, difficulty: 'intermediate', pos: 'noun' },
  { word: 'ANCIENT', length: 7, difficulty: 'intermediate', pos: 'adjective' },
  { word: 'CAPABLE', length: 7, difficulty: 'intermediate', pos: 'adjective' },
  { word: 'CAPTAIN', length: 7, difficulty: 'intermediate', pos: 'noun' },
  { word: 'CAUTION', length: 7, difficulty: 'intermediate', pos: 'noun' },
  { word: 'CENTAUR', length: 7, difficulty: 'intermediate', pos: 'noun' },
  { word: 'CHARIOT', length: 7, difficulty: 'intermediate', pos: 'noun' },
  { word: 'CHIMNEY', length: 7, difficulty: 'intermediate', pos: 'noun' },
  { word: 'CIRCUIT', length: 7, difficulty: 'intermediate', pos: 'noun' },
  { word: 'CLARITY', length: 7, difficulty: 'intermediate', pos: 'noun' },
  { word: 'CLIMATE', length: 7, difficulty: 'intermediate', pos: 'noun' },
  { word: 'COLLIDE', length: 7, difficulty: 'intermediate', pos: 'verb' },
  { word: 'COMBINE', length: 7, difficulty: 'intermediate', pos: 'verb' },
  { word: 'COMFORT', length: 7, difficulty: 'intermediate', pos: 'noun' },
  { word: 'COMPARE', length: 7, difficulty: 'intermediate', pos: 'verb' },
  { word: 'CONCEAL', length: 7, difficulty: 'intermediate', pos: 'verb' },
  { word: 'CONDEMN', length: 7, difficulty: 'intermediate', pos: 'verb' },
  { word: 'CONFINE', length: 7, difficulty: 'intermediate', pos: 'verb' },
  { word: 'CONNECT', length: 7, difficulty: 'intermediate', pos: 'verb' },

  // ── 7-letter ── advanced
  { word: 'ACERBIC', length: 7, difficulty: 'advanced', pos: 'adjective' },
  { word: 'AILMENT', length: 7, difficulty: 'advanced', pos: 'noun' },
  { word: 'ALCHEMY', length: 7, difficulty: 'advanced', pos: 'noun' },
  { word: 'CANDOUR', length: 7, difficulty: 'advanced', pos: 'noun' },
  { word: 'CONCORD', length: 7, difficulty: 'advanced', pos: 'noun' },
  { word: 'CONTRITE', length: 8, difficulty: 'advanced', pos: 'adjective' },
  { word: 'DEBACLE', length: 7, difficulty: 'advanced', pos: 'noun' },
  { word: 'DISCERN', length: 7, difficulty: 'advanced', pos: 'verb' },
  { word: 'DOGGEREL', length: 8, difficulty: 'advanced', pos: 'noun' },
  { word: 'ERUDITE', length: 7, difficulty: 'advanced', pos: 'adjective' },
  { word: 'ESSENCE', length: 7, difficulty: 'advanced', pos: 'noun' },
  { word: 'FRUGAL', length: 6, difficulty: 'advanced', pos: 'adjective' },
  { word: 'GALLANT', length: 7, difficulty: 'advanced', pos: 'adjective' },
  { word: 'GRANITE', length: 7, difficulty: 'advanced', pos: 'noun' },
  { word: 'HARNESS', length: 7, difficulty: 'advanced', pos: 'noun' },
  { word: 'INGRATE', length: 7, difficulty: 'advanced', pos: 'noun' },
  { word: 'LACONIC', length: 7, difficulty: 'advanced', pos: 'adjective' },
  { word: 'LANGUOR', length: 7, difficulty: 'advanced', pos: 'noun' },
  { word: 'NASCENT', length: 7, difficulty: 'advanced', pos: 'adjective' },
  { word: 'OPULENT', length: 7, difficulty: 'advanced', pos: 'adjective' },

  // ── 8-letter ── advanced
  { word: 'ABSOLUTE', length: 8, difficulty: 'advanced', pos: 'adjective' },
  { word: 'ARROGANT', length: 8, difficulty: 'advanced', pos: 'adjective' },
  { word: 'BANKRUPT', length: 8, difficulty: 'advanced', pos: 'adjective' },
  { word: 'BRISTLED', length: 8, difficulty: 'advanced', pos: 'verb' },
  { word: 'CLAMPING', length: 8, difficulty: 'advanced', pos: 'verb' },
  { word: 'CLEMENCY', length: 8, difficulty: 'advanced', pos: 'noun' },
  { word: 'COERCION', length: 8, difficulty: 'advanced', pos: 'noun' },
  { word: 'COLONIAL', length: 8, difficulty: 'advanced', pos: 'adjective' },
  { word: 'COLOSSAL', length: 8, difficulty: 'advanced', pos: 'adjective' },
  { word: 'CONQUEST', length: 8, difficulty: 'advanced', pos: 'noun' },

  // ── 9-letter ── advanced
  { word: 'BRIGADIER', length: 9, difficulty: 'advanced', pos: 'noun' },
  { word: 'CHRONICLE', length: 9, difficulty: 'advanced', pos: 'noun' },
  { word: 'CLAMOROUS', length: 9, difficulty: 'advanced', pos: 'adjective' },
  { word: 'CONFIGURE', length: 9, difficulty: 'advanced', pos: 'verb' },
  { word: 'CONGENIAL', length: 9, difficulty: 'advanced', pos: 'adjective' },
  { word: 'CONTRIVED', length: 9, difficulty: 'advanced', pos: 'adjective' },
  { word: 'CORPULENT', length: 9, difficulty: 'advanced', pos: 'adjective' },
  { word: 'CORRELATE', length: 9, difficulty: 'advanced', pos: 'verb' },
  { word: 'COURTSHIP', length: 9, difficulty: 'advanced', pos: 'noun' },
  { word: 'CRAFTSMAN', length: 9, difficulty: 'advanced', pos: 'noun' },
];
